name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # The group name ensures that previous jobs are cancelled when pushing to
  # pull requets. While pushing to a branch does not cancel previous jobs.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          build: true

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run ESLint
        run: pnpm lint:js

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Check types
        run: pnpm lint:types

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run Stylelint
        run: pnpm lint:css

  jest:
    name: JavaScript unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run Jest
        run: pnpm test:js

  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Run PHP codesniffer
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr
